//
// Created by rubienr on 22.11.15.
//

#ifndef PROJECT_PARTICLEPORTDEFINICIONS_H
#define PROJECT_PARTICLEPORTDEFINICIONS_H

#include <common/PortADefinition.h>
#include <common/PortInteraction.h>

// tx south
#define SOUTH_TX_PIN Pin4
#define SOUTH_TX_DIR ADir
#define SOUTH_TX_PORT AOut

#define SOUTH_TX_SETUP SOUTH_TX_DIR setOut SOUTH_TX_PIN
#define SOUTH_TX_HI SOUTH_TX_PORT setHi SOUTH_TX_PIN
#define SOUTH_TX_LO SOUTH_TX_PORT setLo SOUTH_TX_PIN
#define SOUTH_TX_IS_HI (0 != (SOUTH_TX_PORT getBit SOUTH_TX_PIN))
#define SOUTH_TX_IS_LO (0 == (SOUTH_TX_PORT getBit SOUTH_TX_PIN))

// rx south
#define SOUTH_RX_PIN Pin5
#define SOUTH_RX_DIR ADir
#define SOUTH_RX_PORT AOut

#define SOUTH_RX_SETUP SOUTH_RX_DIR setOut SOUTH_RX_PIN
#define SOUTH_RX_HI SOUTH_RX_PORT setHi SOUTH_RX_PIN
#define SOUTH_RX_LO SOUTH_RX_PORT setLo SOUTH_RX_PIN
#define SOUTH_RX_IS_HI (0 != (SOUTH_RX_PORT getBit SOUTH_RX_PIN))
#define SOUTH_RX_IS_LO (0 == (SOUTH_RX_PORT getBit SOUTH_RX_PIN))

// rx-switch soutch
#define SOUTH_RX_SWITH_PIN Pin6
#define SOUTH_RX_SWITCH_DIR ADir
#define SOUTH_RX_SWITCH_PORT AOut

#define SOUTH_RX_SWITCH_SETUP SOUTH_RX_SWITCH_DIR setOut SOUTH_RX_SWITH_PIN
#define SOUTH_RX_SWITCH_HI SOUTH_RX_SWITCH_PORT setHi SOUTH_RX_SWITH_PIN
#define SOUTH_RX_SWITCH_LO SOUTH_RX_SWITCH_PORT setLo SOUTH_RX_SWITH_PIN
#define SOUTH_RX_SWITCH_IS_HI (0 != (SOUTH_RX_SWITCH_PORT getBit SOUTH_RX_SWITH_PIN))
#define SOUTH_RX_SWITCH_IS_LO (0 == (SOUTH_RX_SWITCH_PORT getBit SOUTH_RX_SWITH_PIN))

// tx north
#define NORTH_TX_PIN Pin1
#define NORTH_TX_DIR ADir
#define NORTH_TX_PORT AOut

#define NORTH_TX_SETUP NORTH_TX_DIR setOut NORTH_TX_PIN
#define NORTH_TX_HI NORTH_TX_PORT setHi NORTH_TX_PIN
#define NORTH_TX_LO NORTH_TX_PORT setLo NORTH_TX_PIN
#define NORTH_TX_IS_HI (0 != (NORTH_TX_PORT getBit NORTH_TX_PIN))
#define NORTH_TX_IS_LO (0 == (NORTH_TX_PORT getBit NORTH_TX_PIN))

// rx north
#define NORTH_RX_PIN Pin2
#define NORTH_RX_DIR ADir
#define NORTH_RX_PORT AOut

#define NORTH_RX_SETUP NORTH_RX_DIR setOut NORTH_RX_PIN
#define NORTH_RX_HI NORTH_RX_PORT setHi NORTH_RX_PIN
#define NORTH_RX_LO NORTH_RX_PORT setLo NORTH_RX_PIN
#define NORTH_RX_IS_HI (0 != (NORTH_RX_PORT getBit NORTH_RX_PIN))
#define NORTH_RX_IS_LO (0 == (NORTH_RX_PORT getBit NORTH_RX_PIN))

// rx-switch north
#define NORTH_RX_SWITH_PIN Pin0
#define NORTH_RX_SWITCH_DIR ADir
#define NORTH_RX_SWITCH_PORT AOut

#define NORTH_RX_SWITCH_SETUP NORTH_RX_SWITCH_DIR setOut NORTH_RX_SWITH_PIN
#define NORTH_RX_SWITCH_HI NORTH_RX_SWITCH_PORT setHi NORTH_RX_SWITH_PIN
#define NORTH_RX_SWITCH_LO NORTH_RX_SWITCH_PORT setLo NORTH_RX_SWITH_PIN
#define NORTH_RX_SWITCH_IS_HI (0 != (NORTH_RX_SWITCH_PORT getBit NORTH_RX_SWITH_PIN))
#define NORTH_RX_SWITCH_IS_LO (0 == (NORTH_RX_SWITCH_PORT getBit NORTH_RX_SWITH_PIN))


// led
#define LED_PIN Pin3
#define LED_DIR ADir
#define LED_PORT AOut
#define LED_SETUP LED_DIR setOut LED_PIN
#define LED_ON LED_PORT setHi LED_PIN
#define LED_OFF LED_PORT setLo LED_PIN
#define LED_IS_ON (0 != (LED_PORT getBit LED_PIN))
#define LED_IS_OFF (0 == (LED_PORT getBit LED_PIN))


// test point
#define TESTPOINT_PIN Pin7
#define TESTPOINT_DIR ADir
#define TESTPOINT_PORT AOut
#define TESTPOINT_SETUP TESTPOINT_DIR setOut TESTPOINT_PIN
#define TESTPOINT_HI TESTPOINT_PORT setHi TESTPOINT_PIN
#define TESTPOINT_LO TESTPOINT_PORT setLo TESTPOINT_PIN
#define TESTPOINT_IS_HI (0 != (TESTPOINT_PORT getBit TESTPOINT_PIN))
#define TESTPOINT_IS_LO (0 == (TESTPOINT_PORT getBit TESTPOINT_PIN))


#endif //PROJECT_PARTICLEPORTDEFINICIONS_H
