/**
 * @author Raoul Rubien 24.09.2016
 *
 * Synchronization related arguments.
 */

#pragma once

#define SYNCHRONIZATION_TYPES_CTORS_FIRST_SYNC_PACKAGE_LOCAL_TIME ((uint16_t) 160)
#define SYNCHRONIZATION_TYPES_CTORS_FAST_SYNC_PACKAGE_SEPARATION ((uint8_t) 20)
#define SYNCHRONIZATION_TYPES_CTORS_SYNC_PACKAGE_SEPARATION ((uint16_t) 140)
//#define SYNCHRONIZATION_TYPES_CTORS_SYNC_PACKAGE_SEPARATION ((uint16_t) 300)
#define SYNCHRONIZATION_TYPES_CTORS_TOTAL_FAST_SYNC_PACKAGES ((uint16_t) 500)
