/**
 * @author Raoul Rubien 16.09.2016
 *
 * Discovery pin change interrupt configuration.
 */

#pragma once

#include <avr/interrupt.h>
#include "common/PortInteraction.h"

#ifdef __AVR_ATtiny1634__ // for production MCU

#  define __DISCOVERY_INTERRUPT_FLAG_NORTH PCIF2
#  define __DISCOVERY_INTERRUPT_FLAG_EAST PCIF1
#  define __DISCOVERY_INTERRUPT_FLAG_SOUTH PCIF0

#  define DISCOVERY_NORTH_INTERRUPT_CLEAR_PENDING \
    (((GIFR & bit(__DISCOVERY_INTERRUPT_FLAG_NORTH)) != 0) ? GIFR = bit(__DISCOVERY_INTERRUPT_FLAG_NORTH):0)

#  define DISCOVERY_EAST_INTERRUPT_CLEAR_PENDING \
    (((GIFR & bit(__DISCOVERY_INTERRUPT_FLAG_EAST)) != 0) ? GIFR = bit(__DISCOVERY_INTERRUPT_FLAG_EAST):0)

#  define DISCOVERY_SOUTH_INTERRUPT_CLEAR_PENDING \
    (((GIFR & bit(__DISCOVERY_INTERRUPT_FLAG_SOUTH)) != 0) ? GIFR = bit(__DISCOVERY_INTERRUPT_FLAG_SOUTH):0)

#  define DISCOVERY_INTERRUPTS_CLEAR_PENDING \
    DISCOVERY_NORTH_INTERRUPT_CLEAR_PENDING; \
    DISCOVERY_EAST_INTERRUPT_CLEAR_PENDING; \
    DISCOVERY_SOUTH_INTERRUPT_CLEAR_PENDING

#  define DISCOVERY_INT_ENABLE \
    (GIMSK setBit (bit(PCIE0) | bit(PCIE1) | bit(PCIE2)))

#  define DISCOVERY_NORTH_INTERRUPT_DISABLE \
    (PCMSK2 unsetBit bit(PCINT17))
#  define DISCOVERY_NORTH_INTERRUPT_ENABLE \
    (PCMSK2 setBit bit(PCINT17))

#  define DISCOVERY_EAST_INTERRUPT_DISABLE \
    (PCMSK1 unsetBit bit(PCINT8))
#  define DISCOVERY_EAST_INTERRUPT_ENABLE \
    (PCMSK1 setBit bit(PCINT8))

#  define DISCOVERY_SOUTH_INTERRUPT_DISABLE \
    (PCMSK0 unsetBit bit(PCINT4))
#  define DISCOVERY_SOUTH_INTERRUPT_ENABLE \
    (PCMSK0 setBit bit(PCINT4))

#  define DISCOVERY_INTERRUPTS_ENABLE \
    DISCOVERY_NORTH_INTERRUPT_ENABLE; \
    DISCOVERY_SOUTH_INTERRUPT_ENABLE; \
    DISCOVERY_EAST_INTERRUPT_ENABLE

#  define DISCOVERY_INTERRUPTS_DISABLE \
    DISCOVERY_NORTH_INTERRUPT_DISABLE; \
    DISCOVERY_SOUTH_INTERRUPT_DISABLE; \
    DISCOVERY_EAST_INTERRUPT_DISABLE

#  define DISCOVERY_INTERRUPTS_SETUP \
    DISCOVERY_INTERRUPTS_CLEAR_PENDING; \
    DISCOVERY_INT_ENABLE

#else
#  if defined(__AVR_ATmega16__) // for simulator MCU

#  define __DISCOVERY_INTERRUPT_FLAG_NORTH \
    INTF2
#  define __DISCOVERY_INTERRUPT_FLAG_EAST \
    INTF1
#  define __DISCOVERY_INTERRUPT_FLAG_SOUTH \
    INTF0

#  define DISCOVERY_NORTH_INTERRUPT_CLEAR_PENDING \
    (((GIFR & bit(__DISCOVERY_INTERRUPT_FLAG_NORTH)) != 0) ? GIFR = bit(__DISCOVERY_INTERRUPT_FLAG_NORTH):0)

#  define DISCOVERY_EAST_INTERRUPT_CLEAR_PENDING \
    (((GIFR & bit(__DISCOVERY_INTERRUPT_FLAG_EAST)) != 0) ? GIFR = bit(__DISCOVERY_INTERRUPT_FLAG_EAST):0)

#  define DISCOVERY_SOUTH_INTERRUPT_CLEAR_PENDING \
    (((GIFR & bit(__DISCOVERY_INTERRUPT_FLAG_SOUTH)) != 0) ? GIFR = bit(__DISCOVERY_INTERRUPT_FLAG_SOUTH):0)

#  define DISCOVERY_INTERRUPTS_CLEAR_PENDING \
    DISCOVERY_NORTH_INTERRUPT_CLEAR_PENDING; \
    DISCOVERY_EAST_INTERRUPT_CLEAR_PENDING; \
    DISCOVERY_SOUTH_INTERRUPT_CLEAR_PENDING
//ISC2 - 0: on falling edge, 1: on rising edge
//(ISCx1, ISCx0) - (0,1): on logic change
#    define __DISCOVERY_INTERRUPTS_SENSE_CONTROL_SETUP \
    MCUCR  setBit (0 << ISC11) | (1 << ISC10) | (0 << ISC01) | (1 << ISC00); \
    MCUCSR setBit (1 << ISC2)

#    define DISCOVERY_NORTH_INTERRUPT_DISABLE GICR unsetBit bit(INT2);
#    define DISCOVERY_NORTH_INTERRUPT_ENABLE GICR setBit bit(INT2);

#    define DISCOVERY_EAST_INTERRUPT_DISABLE GICR unsetBit bit(INT1);
#    define DISCOVERY_EAST_INTERRUPT_ENABLE GICR setBit bit(INT1);

#    define DISCOVERY_SOUTH_INTERRUPT_DISABLE GICR unsetBit bit(INT0);
#    define DISCOVERY_SOUTH_INTERRUPT_ENABLE GICR setBit bit(INT0);

#    define DISCOVERY_INTERRUPTS_ENABLE GICR setBit ((1 << INT0) | (1 << INT1) | (1 << INT2))
#    define DISCOVERY_INTERRUPTS_DISABLE GICR unsetBit ((1 << INT0) | (1 << INT1) | (1 << INT2))

#    define DISCOVERY_INTERRUPTS_SETUP \
    DISCOVERY_INTERRUPTS_CLEAR_PENDING; \
    __DISCOVERY_INTERRUPTS_SENSE_CONTROL_SETUP

#  else
#    error
#  endif
#endif

