/**
 * @author Raoul Rubien 20.07.2016
 *
 * Discovery timer interrupt related configuration.
 */

#pragma once

#include "TimerCounter1.h"

#define __TIMER_NEIGHBOUR_SENSE_PRESCALER_VALUE \
    __TIMER_COUNTER_PRESCALER_8

#define __TIMER_NEIGHBOUR_SENSE_PRESCALER_ENABLE \
    __TIMER1_INTERRUPT_PRESCALER_ENABLE(__TIMER_NEIGHBOUR_SENSE_PRESCALER_VALUE)

#define TIMER_NEIGHBOUR_SENSE_SETUP __TIMER1_INTERRUPT_CLEAR_PENDING; \
    __TIMER1_INTERRUPT_OUTPUT_MODE_DISCONNECTED_SETUP; \
    __TIMER1_INTERRUPT_WAVE_GENERATION_MODE_CTC_SETUP; \
    __TIMER1_INTERRUPT_COMPARE_VALUE_A_SETUP(DEFAULT_NEIGHBOUR_SENSING_COUNTER_COMPARE_VALUE); \
    __TIMER1_INTERRUPT_PRESCALER_DISABLE; \
    __TIMER1_COMPARE_A_INTERRUPT_ENABLE

#define TIMER_NEIGHBOUR_SENSE_DISABLE \
    __TIMER1_COMPARE_A_INTERRUPT_DISABLE

#define TIMER_NEIGHBOUR_SENSE_ENABLE \
    __TIMER1_COMPARE_A_INTERRUPT_ENABLE

#define TIMER_NEIGHBOUR_SENSE_PAUSE \
    __TIMER1_INTERRUPT_PRESCALER_DISABLE

#define TIMER_NEIGHBOUR_SENSE_RESUME \
    __TIMER_NEIGHBOUR_SENSE_PRESCALER_ENABLE

#define TIMER_NEIGHBOUR_SENSE_COUNTER_VALUE \
    TCNT1
